#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────────────────
# build_config.sh — يُولِّد public/config.js من Environment Variables
# يُنفَّذ تلقائياً بواسطة Netlify قبل كل عملية نشر
#
# المتغيرات المطلوبة في Netlify Dashboard → Site settings → Environment variables:
#   API_BASE             — رابط الـ backend   مثال: https://api.yourapp.railway.app
#   SUPABASE_URL         — رابط مشروع Supabase مثال: https://xxxx.supabase.co
#   SUPABASE_ANON_KEY    — المفتاح العام فقط   (anon/public key)
#
# ⚠️  لا تضع SUPABASE_SERVICE_ROLE_KEY هنا أبداً — يبقى في backend فقط
# ─────────────────────────────────────────────────────────────────────────────
set -e

API_BASE="${API_BASE:-}"
SUPABASE_URL="${SUPABASE_URL:-}"
SUPABASE_ANON_KEY="${SUPABASE_ANON_KEY:-}"

cat > public/config.js << JSEOF
// AUTO-GENERATED by scripts/build_config.sh — لا تعدل هذا الملف يدوياً في الإنتاج
// Generated at: $(date -u +"%Y-%m-%dT%H:%M:%SZ")
window.API_BASE        = '${API_BASE}';
window.SUPABASE_URL    = '${SUPABASE_URL}';
window.SUPABASE_ANON_KEY = '${SUPABASE_ANON_KEY}';
JSEOF

echo "✅  config.js generated:"
echo "    API_BASE        = ${API_BASE:-(empty)}"
echo "    SUPABASE_URL    = ${SUPABASE_URL:-(empty)}"
echo "    SUPABASE_ANON_KEY = ${SUPABASE_ANON_KEY:0:20}... (truncated)"
